[BandMeasure0]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=0

[BandMeasure1]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=1

[BandMeasure2]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=2

[BandMeasure3]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=3

[BandMeasure4]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=4

[BandMeasure5]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=5

[BandMeasure6]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=6

[BandMeasure7]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=7

[BandMeasure8]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=8

[BandMeasure9]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=9

[BandMeasure10]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=10

[BandMeasure11]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=11

[BandMeasure12]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=12

[BandMeasure13]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=13

[BandMeasure14]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=14

[BandMeasure15]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=15

[BandMeasure16]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=16

[BandMeasure17]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=17

[BandMeasure18]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=18

[BandMeasure19]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=19

[BandMeasure20]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=20

[BandMeasure21]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=21

[BandMeasure22]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=22

[BandMeasure23]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=23

[BandMeasure24]
Measure=Plugin
Plugin=AudioLevel
Parent=ParentAudio
Type=Band
BandIdx=24

