[BandMeter0]
Meter=Bar
MeasureName=BandMeasure0
X=0
Y=0
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter1]
Meter=Bar
MeasureName=BandMeasure1
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter2]
Meter=Bar
MeasureName=BandMeasure2
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter3]
Meter=Bar
MeasureName=BandMeasure3
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter4]
Meter=Bar
MeasureName=BandMeasure4
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter5]
Meter=Bar
MeasureName=BandMeasure5
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter6]
Meter=Bar
MeasureName=BandMeasure6
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter7]
Meter=Bar
MeasureName=BandMeasure7
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter8]
Meter=Bar
MeasureName=BandMeasure8
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter9]
Meter=Bar
MeasureName=BandMeasure9
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter10]
Meter=Bar
MeasureName=BandMeasure10
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter11]
Meter=Bar
MeasureName=BandMeasure11
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter12]
Meter=Bar
MeasureName=BandMeasure12
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter13]
Meter=Bar
MeasureName=BandMeasure13
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter14]
Meter=Bar
MeasureName=BandMeasure14
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter15]
Meter=Bar
MeasureName=BandMeasure15
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter16]
Meter=Bar
MeasureName=BandMeasure16
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter17]
Meter=Bar
MeasureName=BandMeasure17
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter18]
Meter=Bar
MeasureName=BandMeasure18
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter19]
Meter=Bar
MeasureName=BandMeasure19
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter20]
Meter=Bar
MeasureName=BandMeasure20
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter21]
Meter=Bar
MeasureName=BandMeasure21
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter22]
Meter=Bar
MeasureName=BandMeasure22
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter23]
Meter=Bar
MeasureName=BandMeasure23
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

[BandMeter24]
Meter=Bar
MeasureName=BandMeasure24
X=10R
Y=0r
W=20
H=100
BarColor=30,102,240,180
BarOrientation=Vertical

